AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*

BlockLength:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

Documentation:
  Enabled: false

LineLength:
  Max: 120
  Exclude:
    - spec/**/*

MethodLength:
  Max: 30

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

